spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <CLIENT_ID>
            clientSecret: <CLIENT_ID>
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile