spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${CLIENT-ID}"
            client-secret: "${CLIENT-SECRET}"
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
