spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
  rabbitmq:
    addresses: "${SPRING_RABBITMQ_ADDRESSES}"
  mail:
    host: "${SPRING_MAIL_HOST}"
    port: "${SPRING_MAIL_PORT}"
    username: "${SPRING_MAIL_USERNAME}"
    password: "${SPRING_MAIL_PASSWORD}"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${CLIENT-ID}"
            client-secret: "${CLIENT-SECRET}"
            scope:
              - email
              - profile